services:
  backend:
    image: mdanamulhasanrony/food-delivery-app-backend
    container_name: food-delivery-app-backend
    restart: unless-stopped
    ports:
      - "8080:8080"

    environment:
      SPRING_DATA_MONGODB_URI: "SPRING_DATA_MONGODB_URI:mongodb+srv://root:password-admin-root@cluster0.poiyyuf.mongodb.net/food_delivery_application?retryWrites=true&w=majority"

      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-498502c0fe7d53807379353f7cb75de227f635981762319b39a2aab6cf92a995}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY:-dummy-key}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY:-dummy-secret}
      AWS_REGION: us-east-1
      AWS_BUCKETNAME: test-bucket-rony
      SSLCOMMERZ_STORE_ID: ${SSLCOMMERZ_STORE_ID:-mycom696fd1d6c7d22}
      SSLCOMMERZ_SECRET_KEY: ${SSLCOMMERZ_SECRET_KEY:-mycom696fd1d6c7d22@ssl}
      FRONTEND_BASE_URL: "http://localhost:5173"
      BACKEND_BASE_URL: "http://54.160.145.92:8080"
